### PR TITLE
Changed file format, repaired tags...

### PR DESCRIPTION
**Pull request by kyngs**
... like \<details> or \<summary>

### CODE REVIEW

**Comment by kyngs** [comment]
uwu is anyone here?

**Comment by Daniel-Liu-c0deb0t** [comment]
hi sorry for the delay. a lot of ppl have asked about changing the file format, but i've always held off on it since the uwu'd readme is directly generated from the non-uwu'd version and i don't want to keep maintaining the uwu'd version manually as uwuify changes.

**Comment by kyngs** [comment]
Understandable have a great day.

**Comment by Daniel-Liu-c0deb0t** [comment]
sorry :'(

**Comment by kyngs** [comment]
Tho when I think about it, couldn't you set up a GitHub workflow to automatically generate it?

**Comment by Daniel-Liu-c0deb0t** [comment]
yes, but then fixing up the tags would still be annoying

**Pull request closed without merging**
